remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "contrast"
title: "Blog | Derek Williams"
description: "Depth articles on data and software engineering with a point of view. I may digress into Agile process, leadership, and other topics."
email: softwaresalt@gmail.com

plugins:
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true

author:
  name: "Derek Williams"
  avatar: "/assets/images/avatar.me.png" # We will add this file in Step 2
  bio: "Software/Data Engineer working consulting space for 25+ years. Ex Avanaut. I find my flow in building things."
  location: "Seattle, WA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/softwaresalt"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/softwaresalt"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/softwaresalt"
